version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: pts-postgres
    environment:
      POSTGRES_DB: portfoliodb
      POSTGRES_USER: portfolio_user
      POSTGRES_PASSWORD: portfolio_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: portfolio-tracker-service
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/portfoliodb
      SPRING_DATASOURCE_USERNAME: portfolio_user
      SPRING_DATASOURCE_PASSWORD: portfolio_pass
      APP_JWT_SECRET: c3VwZXJfc2VjcmV0X2NoYW5nZV9tZV9pbl9kZXY=
    ports:
      - "8080:8080"

volumes:
  postgres_data:
